export namespace config {
	
	export class AppSettings {
	    defaultChannel: string;
	    fontSize: number;
	    showTimestamps: boolean;
	    timestampFormat: string;
	    showBadges: boolean;
	    showFollows: boolean;
	    channelBadgeMode: string;
	    iconColor: string;
	    maxMessages: number;
	    oauthToken: string;
	    username: string;
	    userId: string;
	    clientId: string;
	    joinedChannels: string[];
	    channelColors: Record<string, string>;
	    ttsEnabled: boolean;
	    ttsVolume: number;
	    ttsEngine: string;
	    ttsVoice: string;
	    ttsVoiceLocal: string;
	    ttsSpeed: number;
	    ttsAudioDevice: string;
	    ttsSkipHotkey: string;
	    ttsAllMessages: boolean;
	    ttsRepliesOnly: boolean;
	    ttsHighlightedOnly: boolean;
	    ttsSubscribersOnly: boolean;
	    ttsVipOnly: boolean;
	    ttsModOnly: boolean;
	    ttsIncludeUsername: boolean;
	    ttsIncludeLinks: boolean;
	    ttsIncludeEmotes: boolean;
	    ttsIncludeEmoji: boolean;
	    ttsIncludeMentions: boolean;
	    ttsRemoveWords: string;
	    ignoreCommands: boolean;
	    commandPrefixes: string;
	    ignoreEmotesOnly: boolean;
	    ttsFilterEmotes: boolean;
	    ignoredUsers: string[];
	    hideIgnoredFromChat: boolean;
	    alwaysOnTop: boolean;
	    fontFamily: string;
	    messageSpacing: string;
	    textAlign: string;
	    proxyEnabled: boolean;
	    proxyType: string;
	    proxyAddress: string;
	    proxyAuth: boolean;
	    proxyUser: string;
	    proxyPassword: string;
	    wireGuardPrivateKey: string;
	    wireGuardPublicKey: string;
	    wireGuardAddress: string;
	    wireGuardDNS: string;
	    wireGuardEndpoint: string;
	    wireGuardAllowedIPs: string;
	    musicStyle: string;
	    musicAccentColor: string;
	    musicShowCover: boolean;
	    musicShowVisualizer: boolean;
	    musicShowArtist: boolean;
	    musicHideOnPause: boolean;
	    musicPauseDelay: number;
	    musicScale: number;
	    musicBgOpacity: number;
	
	    static createFrom(source: any = {}) {
	        return new AppSettings(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.defaultChannel = source["defaultChannel"];
	        this.fontSize = source["fontSize"];
	        this.showTimestamps = source["showTimestamps"];
	        this.timestampFormat = source["timestampFormat"];
	        this.showBadges = source["showBadges"];
	        this.showFollows = source["showFollows"];
	        this.channelBadgeMode = source["channelBadgeMode"];
	        this.iconColor = source["iconColor"];
	        this.maxMessages = source["maxMessages"];
	        this.oauthToken = source["oauthToken"];
	        this.username = source["username"];
	        this.userId = source["userId"];
	        this.clientId = source["clientId"];
	        this.joinedChannels = source["joinedChannels"];
	        this.channelColors = source["channelColors"];
	        this.ttsEnabled = source["ttsEnabled"];
	        this.ttsVolume = source["ttsVolume"];
	        this.ttsEngine = source["ttsEngine"];
	        this.ttsVoice = source["ttsVoice"];
	        this.ttsVoiceLocal = source["ttsVoiceLocal"];
	        this.ttsSpeed = source["ttsSpeed"];
	        this.ttsAudioDevice = source["ttsAudioDevice"];
	        this.ttsSkipHotkey = source["ttsSkipHotkey"];
	        this.ttsAllMessages = source["ttsAllMessages"];
	        this.ttsRepliesOnly = source["ttsRepliesOnly"];
	        this.ttsHighlightedOnly = source["ttsHighlightedOnly"];
	        this.ttsSubscribersOnly = source["ttsSubscribersOnly"];
	        this.ttsVipOnly = source["ttsVipOnly"];
	        this.ttsModOnly = source["ttsModOnly"];
	        this.ttsIncludeUsername = source["ttsIncludeUsername"];
	        this.ttsIncludeLinks = source["ttsIncludeLinks"];
	        this.ttsIncludeEmotes = source["ttsIncludeEmotes"];
	        this.ttsIncludeEmoji = source["ttsIncludeEmoji"];
	        this.ttsIncludeMentions = source["ttsIncludeMentions"];
	        this.ttsRemoveWords = source["ttsRemoveWords"];
	        this.ignoreCommands = source["ignoreCommands"];
	        this.commandPrefixes = source["commandPrefixes"];
	        this.ignoreEmotesOnly = source["ignoreEmotesOnly"];
	        this.ttsFilterEmotes = source["ttsFilterEmotes"];
	        this.ignoredUsers = source["ignoredUsers"];
	        this.hideIgnoredFromChat = source["hideIgnoredFromChat"];
	        this.alwaysOnTop = source["alwaysOnTop"];
	        this.fontFamily = source["fontFamily"];
	        this.messageSpacing = source["messageSpacing"];
	        this.textAlign = source["textAlign"];
	        this.proxyEnabled = source["proxyEnabled"];
	        this.proxyType = source["proxyType"];
	        this.proxyAddress = source["proxyAddress"];
	        this.proxyAuth = source["proxyAuth"];
	        this.proxyUser = source["proxyUser"];
	        this.proxyPassword = source["proxyPassword"];
	        this.wireGuardPrivateKey = source["wireGuardPrivateKey"];
	        this.wireGuardPublicKey = source["wireGuardPublicKey"];
	        this.wireGuardAddress = source["wireGuardAddress"];
	        this.wireGuardDNS = source["wireGuardDNS"];
	        this.wireGuardEndpoint = source["wireGuardEndpoint"];
	        this.wireGuardAllowedIPs = source["wireGuardAllowedIPs"];
	        this.musicStyle = source["musicStyle"];
	        this.musicAccentColor = source["musicAccentColor"];
	        this.musicShowCover = source["musicShowCover"];
	        this.musicShowVisualizer = source["musicShowVisualizer"];
	        this.musicShowArtist = source["musicShowArtist"];
	        this.musicHideOnPause = source["musicHideOnPause"];
	        this.musicPauseDelay = source["musicPauseDelay"];
	        this.musicScale = source["musicScale"];
	        this.musicBgOpacity = source["musicBgOpacity"];
	    }
	}

}

