// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectChannel(arg1) {
  return window['go']['main']['App']['ConnectChannel'](arg1);
}

export function DisconnectChannel() {
  return window['go']['main']['App']['DisconnectChannel']();
}

export function GetEmotes() {
  return window['go']['main']['App']['GetEmotes']();
}

export function GetGlobalBadges() {
  return window['go']['main']['App']['GetGlobalBadges']();
}

export function GetJoinedChannels() {
  return window['go']['main']['App']['GetJoinedChannels']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTTSVoices() {
  return window['go']['main']['App']['GetTTSVoices']();
}

export function GetWidgetThemes() {
  return window['go']['main']['App']['GetWidgetThemes']();
}

export function GetWidgetURL() {
  return window['go']['main']['App']['GetWidgetURL']();
}

export function JoinChannel(arg1) {
  return window['go']['main']['App']['JoinChannel'](arg1);
}

export function LeaveChannel(arg1) {
  return window['go']['main']['App']['LeaveChannel'](arg1);
}

export function LogoutTwitch() {
  return window['go']['main']['App']['LogoutTwitch']();
}

export function OpenThemesDir() {
  return window['go']['main']['App']['OpenThemesDir']();
}

export function ResizeWindowForSettings(arg1) {
  return window['go']['main']['App']['ResizeWindowForSettings'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SpeakText(arg1, arg2) {
  return window['go']['main']['App']['SpeakText'](arg1, arg2);
}

export function StartTwitchAuth() {
  return window['go']['main']['App']['StartTwitchAuth']();
}
