// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectChannel(arg1) {
  return window['go']['main']['App']['ConnectChannel'](arg1);
}

export function DisconnectChannel() {
  return window['go']['main']['App']['DisconnectChannel']();
}

export function GetJoinedChannels() {
  return window['go']['main']['App']['GetJoinedChannels']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function JoinChannel(arg1) {
  return window['go']['main']['App']['JoinChannel'](arg1);
}

export function LeaveChannel(arg1) {
  return window['go']['main']['App']['LeaveChannel'](arg1);
}

export function LogoutTwitch() {
  return window['go']['main']['App']['LogoutTwitch']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartTwitchAuth() {
  return window['go']['main']['App']['StartTwitchAuth']();
}
