// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectChannel(arg1) {
  return window['go']['main']['App']['ConnectChannel'](arg1);
}

export function DisconnectChannel() {
  return window['go']['main']['App']['DisconnectChannel']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}
