// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {eventbus} from '../models';
import {config} from '../models';

export function ConnectTwitch(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DisconnectTwitch():Promise<Record<string, any>>;

export function GetInitialEvents():Promise<Array<eventbus.StreamEvent>>;

export function GetMode():Promise<string>;

export function GetSettings():Promise<config.AppConfig>;

export function GetTTSStatus():Promise<string|number>;

export function GetTwitchStatus():Promise<Record<string, any>>;

export function OpenChatWindow():Promise<void>;

export function OpenSettingsWindow():Promise<void>;

export function SaveSettings(arg1:config.AppConfig):Promise<boolean>;

export function SendChatMessage(arg1:string):Promise<eventbus.StreamEvent>;

export function SendSimulatedDonate(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function TestTTS(arg1:string,arg2:string):Promise<void>;
